[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# AUDITOR REQUIRED: Pin exact compiler settings for reproducible builds
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200  # PINNED: Do not change without auditor approval
evm_version = "paris"
bytecode_hash = "none"  # AUDITOR REQUIRED: Prevents metadata hash variability
via_ir = true  # AUDITOR REQUIRED: Stack depth (document if changing)

# AUDITOR NOTE: Any changes to build settings require bytecode re-verification
# Current deployment hashes recorded in BUILD_INFO.md

gas_reports = ["SmartAccount", "SpendingLimitModule", "SessionKeyValidator", "SocialRecoveryModule"]
fs_permissions = [{ access = "read-write", path = "./deployments" }]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
local = "http://localhost:8545"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }