[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
gas_reports = ["SmartAccount", "SpendingLimitModule", "SessionKeyValidator", "SocialRecoveryModule"]
fs_permissions = [{ access = "read-write", path = "./deployments" }]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
local = "http://localhost:8545"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }